[package]
name = "accumulators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
rusqlite = "0.25.3"
anyhow = "1.0"
async-trait = "0.1.74"
hex = "0.4.3"
sha3 = "0.10.8"
starknet = "0.6.0"
primitive-types = "0.10"
uuid = { version = "1.4.1", features = ["v4"] }
parking_lot = "0.12.1"
starknet-crypto = "0.6.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "mmr_benchmark"
harness = false

[features]
default = ["store", "hasher"]
all = ["store", "sqlite", "hasher", "keccak", "poseidon", "pedersen", "mmr", "infinitely_stackable_mmr", "merkle_tree", "incremental_merkle_tree"]
store = []
sqlite = ["store"]
hasher = []
keccak = ["hasher"]
poseidon = ["hasher"]
pedersen = ["hasher"]
mmr = ["hasher", "store"]
infinitely_stackable_mmr = ["mmr"]
merkle_tree = ["hasher", "store"]
incremental_merkle_tree = ["merkle_tree"]